# Image Translator Configuration

# OCR Settings
ocr:
  engine: "paddleocr"  # Options: paddleocr, easyocr
  languages: ["en", "ch"]  # English and Chinese
  use_angle_cls: true  # Detect text orientation
  use_gpu: false  # CPU-only for macOS
  det_db_thresh: 0.3  # Text detection threshold
  det_db_box_thresh: 0.6  # Bounding box threshold
  rec_batch_num: 6  # Batch size for recognition
  drop_score: 0.5  # Minimum confidence score
  enable_mkldnn: true  # Intel CPU optimization

# Translation Settings
translation:
  engine: "google"  # Options: google, deepl, argos (offline)
  source_lang: "auto"  # auto-detect or specify
  target_lang: "zh-CN"  # zh-CN (Simplified) or zh-TW (Traditional)
  batch_size: 50  # Batch translations for efficiency
  cache_translations: true  # Cache to reduce API calls
  timeout: 30  # API timeout in seconds

# Inpainting Settings
inpainting:
  method: "telea"  # Options: telea, ns (Navier-Stokes)
  radius: 5  # Inpainting radius in pixels
  expand_mask: 2  # Expand mask by N pixels for cleaner removal

# Font Settings
fonts:
  chinese_simplified: "/System/Library/Fonts/PingFang.ttc"
  chinese_traditional: "/System/Library/Fonts/PingFang.ttc"
  fallback: "/System/Library/Fonts/STHeiti Medium.ttc"
  min_font_size: 8
  max_font_size: 200
  line_spacing: 1.3
  
# Text Rendering
rendering:
  auto_scale: true  # Scale font to fit bounding box
  preserve_color: true  # Match original text color
  preserve_style: true  # Match bold/italic
  text_alignment: "left"  # Options: left, center, right
  wrap_text: true  # Enable multi-line wrapping
  
# Document Processing
documents:
  pdf_dpi: 300  # DPI for PDF rendering
  preserve_structure: true  # Maintain document layout
  process_images: true  # Extract and translate images in PDFs
  
# Batch Processing
batch:
  num_workers: 4  # Parallel processing workers (CPU cores)
  chunk_size: 10  # Files per batch
  progress_bar: true
  save_intermediate: true  # Save results after each file
  continue_on_error: true  # Don't stop on single file failure

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "image_translator.log"
  log_format: "json"  # Options: json, text
  
# Output
output:
  format: "png"  # Default output format
  quality: 95  # For JPEG output
  preserve_metadata: true
  suffix: "_translated"  # Append to filename